import { createHash } from "node:crypto";
import { is, SQL, Table, getTableName } from "drizzle-orm";
import { getTableConfig, SQLiteSyncDialect } from "drizzle-orm/sqlite-core";
import * as source from "../src/server/db/schema";

export const quote = (name: string) => '"' + name.replaceAll('"', '""') + '"';
export const tableName = (name: string) => `hob_private.${quote(name)}`;
export const tables = Object.values(source).filter(value => is(value, Table)).map(table => getTableConfig(table)).sort((a, b) => a.name.localeCompare(b.name));
const literal = (value: unknown): string => typeof value === "string" ? "'" + value.replaceAll("'", "''") + "'" : String(value);
const safeName = (name: string) => name.length <= 60 ? name : name.slice(0, 47) + "_" + createHash("sha256").update(name).digest("hex").slice(0, 12);
const dialect = new SQLiteSyncDialect();
function expression(value: SQL): string {
  const query = dialect.sqlToQuery(value);
  if (query.params.length) throw new Error("Parameterized schema expression requires explicit migration");
  return query.sql.replace(/"[^"]+"\."([^"]+)"/g, '"$1"');
}

/** Generate from checked-in schema, never from private row contents. */
export function generateSchema(): string {
  const statements = [
    "-- Generated by migration/postgres-schema.ts from the checked-in SQLite schema.",
    "-- All source tables remain private; later reviewed RPCs expose only allowed fields.",
    "CREATE SCHEMA hob_private;",
    "REVOKE ALL ON SCHEMA hob_private FROM PUBLIC;",
    "CREATE TABLE hob_private.import_marker (source_hash text PRIMARY KEY, imported_at timestamptz NOT NULL DEFAULT now());",
    "ALTER TABLE hob_private.import_marker ENABLE ROW LEVEL SECURITY;",
  ];
  for (const table of tables) {
    const columns = table.columns.map(column => {
      const type = column.columnType === "SQLiteTimestamp" ? "timestamptz" : column.columnType === "SQLiteBoolean" ? "boolean" : column.columnType === "SQLiteTextJson" ? "jsonb" : column.columnType === "SQLiteInteger" ? "integer" : column.columnType === "SQLiteReal" ? "double precision" : "text";
      const auto = "autoIncrement" in column && column.autoIncrement;
      let declaration = `${quote(column.name)} ${type}${auto ? " GENERATED BY DEFAULT AS IDENTITY" : ""}${column.primary ? " PRIMARY KEY" : ""}${column.notNull ? " NOT NULL" : ""}`;
      if (column.default !== undefined) declaration += " DEFAULT " + (is(column.default, SQL) ? expression(column.default) : literal(column.default));
      else if (column.defaultFn && type === "timestamptz") declaration += " DEFAULT now()";
      if (column.isUnique) declaration += " UNIQUE";
      if (column.enumValues?.length) declaration += ` CHECK (${quote(column.name)} IN (${column.enumValues.map(literal).join(",")}))`;
      return declaration;
    });
    for (const pk of table.primaryKeys) columns.push(`PRIMARY KEY (${pk.columns.map(c => quote(c.name)).join(",")})`);
    for (const unique of table.uniqueConstraints) columns.push(`UNIQUE (${unique.columns.map(c => quote(c.name)).join(",")})`);
    for (const check of table.checks) columns.push(`CHECK (${expression(check.value)})`);
    statements.push(`CREATE TABLE ${tableName(table.name)} (\n  ${columns.join(",\n  ")}\n);`);
    statements.push(`ALTER TABLE ${tableName(table.name)} ENABLE ROW LEVEL SECURITY;`);
  }
  for (const table of tables) {
    for (const foreignKey of table.foreignKeys) {
      const ref = foreignKey.reference();
      statements.push(`ALTER TABLE ${tableName(table.name)} ADD FOREIGN KEY (${ref.columns.map(c => quote(c.name)).join(",")}) REFERENCES ${tableName(getTableName(ref.foreignTable))} (${ref.foreignColumns.map(c => quote(c.name)).join(",")})${foreignKey.onDelete ? " ON DELETE " + foreignKey.onDelete : ""}${foreignKey.onUpdate ? " ON UPDATE " + foreignKey.onUpdate : ""} DEFERRABLE INITIALLY DEFERRED;`);
    }
    for (const index of table.indexes) {
      const cfg = index.config;
      statements.push(`CREATE ${cfg.unique ? "UNIQUE " : ""}INDEX ${quote(safeName(cfg.name))} ON ${tableName(table.name)} (${cfg.columns.map(c => is(c, SQL) ? expression(c) : quote(c.name)).join(",")})${cfg.where ? " WHERE " + expression(cfg.where) : ""};`);
    }
  }
  statements.push("REVOKE ALL ON ALL TABLES IN SCHEMA hob_private FROM PUBLIC;", "REVOKE ALL ON ALL SEQUENCES IN SCHEMA hob_private FROM PUBLIC;");
  return statements.join("\n\n") + "\n";
}
