-- MIGRATION SLOT NOTE (Task 31 brief): this is the controller-assigned slot 0010. Generated with
-- `drizzle-kit generate`, then hand-trimmed and hand-extended — see the two notes below.
--
-- HAND-TRIMMED (not a schema change): drizzle-kit's generator diffed against `meta/0008_snapshot.
-- json`, whose OWN `tables` list is missing `achievements` — a pre-existing artifact of the
-- achievements-engine (0007) and recap-voice-learning (0008) branches having been developed in
-- parallel and merged without ever re-generating a consolidated snapshot (see 0008_first_reaper.
-- sql's own "INTEGRATION CONSTRAINT" comment for the same parallel-branch merge mechanism). The
-- raw generator output therefore included a redundant `CREATE TABLE achievements ...` + its 4
-- indexes, which would fail outright against any real DB (that table already exists once 0000-0008
-- have applied in order, created by migration 0007). Removed here by hand; only the genuine new
-- table (`pickem_picks`) remains below. `meta/0010_snapshot.json` itself is NOT affected by this —
-- it was generated by introspecting the full, correct `schema.ts` (all 38 tables, achievements
-- included), so it accurately represents the schema state after this migration applies.
CREATE TABLE `pickem_picks` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`manager_id` integer,
	`is_algorithm` integer DEFAULT false NOT NULL,
	`season` integer NOT NULL,
	`week` integer NOT NULL,
	`matchup_id` integer NOT NULL,
	`picked_franchise_id` integer NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`manager_id`) REFERENCES `managers`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE INDEX `pickem_picks_season_week_idx` ON `pickem_picks` (`season`,`week`);--> statement-breakpoint
CREATE UNIQUE INDEX `pickem_picks_manager_id_matchup_id_unique` ON `pickem_picks` (`manager_id`,`matchup_id`);--> statement-breakpoint
-- HAND-ADDED (not drizzle-kit generated, same precedent as 0008_first_reaper.sql's trailing UPDATE
-- statement): drizzle's schema-level `unique()` builder can't express a partial/filtered index.
-- `manager_id` is NULL for every "The Algorithm" pseudo-entrant row (isAlgorithm = true — see
-- schema.ts's pickemPicks docstring and src/server/sync/pickem-lock.ts), and SQL treats NULL as
-- distinct from NULL for uniqueness purposes, so the composite unique index above (which covers
-- every real human pick) does nothing to stop duplicate algorithm rows for the same matchup. This
-- partial index closes that other half: at most one algorithm-authored pick per matchup, full stop.
CREATE UNIQUE INDEX `pickem_picks_algorithm_matchup_unique` ON `pickem_picks` (`matchup_id`) WHERE `is_algorithm` = 1;
