import {useState} from 'react';
import type {PageData} from '../api/pages';
import Link from '../components/Link';
import {RecapMarkdownView} from '../../../src/features/recaps/markdown-view';
import {Empty,Franchise,GridTable,label,name,number,PageHeader,Pagination,Section,SeasonLinks} from './LeagueParts';
import {RECORD_KEY_META} from '../../../src/shared/records';
import type {RecordKey} from '../../../src/engines';

export function Recaps({data,detail}:{data:PageData;detail:boolean}){return <><PageHeader eyebrow="League dispatches" title="Recaps"/>{detail?<><Link href="/recaps" className="my-5 block text-kelly">← All recaps</Link>{data.recaps.length?data.recaps.map(r=><Section key={r.id} title={`${r.season} · Week ${r.week}`}><RecapMarkdownView markdown={r.markdownFinal??''}/></Section>):<Empty>No published recap was found for this week.</Empty>}</>:<Section title="Published recaps">{data.recaps.length?<div className="grid gap-4 sm:grid-cols-2">{data.recaps.map(r=><Link key={r.id} href={`/recaps/${r.season}/${r.week}`} className="border border-line-sheet p-5"><h2 className="display text-2xl text-kelly">{r.season} · Week {r.week}</h2><p className="mt-2 text-sm">{label(r.style)}</p></Link>)}</div>:<Empty>No recaps have been published yet.</Empty>}</Section>}</>;}

export function Transactions({data,search}:{data:PageData;search:string}){const [filter,setFilter]=useState('all');const visible=data.transactions.filter(t=>filter==='all'||t.type===filter);return <><PageHeader eyebrow="League activity" title="Transactions"/><SeasonLinks data={data} path="transactions"/><label className="text-sm">Type <select className="ml-3 border border-line-sheet bg-sheet p-2" value={filter} onChange={e=>setFilter(e.target.value)}>{['all','trade','waiver','freeagent','drop','lineup'].map(t=><option key={t} value={t}>{label(t)}</option>)}</select></label><Section title="Roster moves">{visible.length?visible.map(t=><article key={t.id} className="mb-4 border border-line-sheet p-5"><div className="flex flex-wrap justify-between gap-2"><h3 className="display text-lg">{label(t.type)} · {label(t.status)}</h3><span className="text-xs text-muted">{t.processedAt?new Date(t.processedAt).toLocaleString():t.proposedAt?new Date(t.proposedAt).toLocaleString():'Date unavailable'}</span></div>{t.bidAmount!==null&&<p className="mt-2 text-sm">Bid: ${number(t.bidAmount,0)}</p>}<div className="mt-4"><GridTable head={['Franchise','Action','Player','Source']} rows={data.transactionItems.filter(i=>i.transactionId===t.id).map(i=>[<Franchise key={i.id} data={data} id={data.teamSeasons.find(s=>s.id===i.teamSeasonId)?.franchiseId??null}/>,label(i.action),data.players.find(p=>p.espnPlayerId===i.playerId)?.fullName??`Player ${i.playerId}`,i.source==='inferred'?'Inferred from roster changes':'ESPN'])}/></div></article>):<Empty>No matching transactions on this page.</Empty>}<Pagination path="/transactions" search={search} count={data.transactions.length}/></Section></>;}

export function Timeline({data}:{data:PageData}){const [year,setYear]=useState('all');const [type,setType]=useState('all');
 const entries:{season:number;week:number|null;title:string;detail:string;href:string;type:string}[]=[];
 for(const f of data.franchises){entries.push({season:f.joinedSeason,week:null,title:'New franchise',detail:`${f.canonicalName} joined the league.`,href:`/franchises/${f.id}`,type:'arrival'});if(f.departedSeason!==null)entries.push({season:f.departedSeason,week:null,title:'Departure',detail:`${f.canonicalName} left the league.`,href:`/franchises/${f.id}`,type:'departure'});}
 for(const s of data.seasonStats){if(s.champion||s.sacko)entries.push({season:s.season,week:null,title:s.champion?'Champion':'Sacko',detail:`${name(data,s.franchiseId)} · ${s.season}`,href:`/seasons/${s.season}`,type:s.champion?'championship':'sacko'});}
 for(const r of data.beltReigns)entries.push({season:r.startSeason,week:r.startWeek,title:r.wonFromFranchiseId?'Belt changes hands':'Belt awarded',detail:r.wonFromFranchiseId?`${name(data,r.franchiseId)} took the belt from ${name(data,r.wonFromFranchiseId)}.`:`${name(data,r.franchiseId)} was awarded the vacant belt.`,href:'/belt',type:'belt'});
 for(const r of data.records){const meta=RECORD_KEY_META[r.recordKey as RecordKey];entries.push({season:r.season,week:r.week,title:meta?.label??label(r.recordKey),detail:`${name(data,r.franchiseId)} · ${meta?.format(r.value)??number(r.value)}`,href:'/records',type:'record'});}
 const visible=entries.filter(e=>(year==='all'||e.season===Number(year))&&(type==='all'||e.type===type)).sort((a,b)=>b.season-a.season||(b.week??99)-(a.week??99));
 return <><PageHeader eyebrow="The Archive" title="Timeline"/><div className="my-5 flex flex-wrap gap-5"><label>Season <select className="border border-line-sheet bg-sheet p-2" value={year} onChange={e=>setYear(e.target.value)}><option value="all">All seasons</option>{data.seasons.map(s=><option key={s.season}>{s.season}</option>)}</select></label><label>Event <select className="border border-line-sheet bg-sheet p-2" value={type} onChange={e=>setType(e.target.value)}>{['all','championship','sacko','belt','record','arrival','departure'].map(t=><option key={t} value={t}>{label(t)}</option>)}</select></label></div>{visible.length?visible.map((e,i)=><article key={i} className="mb-4 border-l-2 border-kelly bg-sheet-raised p-5"><p className="display text-xs tracking-widest text-muted">{e.season}{e.week?` · Week ${e.week}`:''}</p><Link href={e.href} className="display mt-2 block text-xl text-kelly">{e.title}</Link><p className="mt-2 text-sm">{e.detail}</p></article>):<Empty/>}</>;
}
