import {useRef,useState,type FormEvent} from 'react';
import {useNavigate} from 'react-router-dom';
import type {PageData} from '../api/pages';
import {supabase} from '../lib/supabase';
import Link from '../components/Link';
import {RecapMarkdownView} from '../../../src/features/recaps/markdown-view';
import {Empty,GridTable,name,PageHeader,Section} from './LeagueParts';

const inputClass='block w-full border border-line-sheet bg-sheet-raised p-3 text-sm';
const buttonClass='display border border-kelly bg-kelly-deep px-4 py-2 text-white disabled:opacity-50';
function useAction(reload:()=>void){const [busy,setBusy]=useState(false),[message,setMessage]=useState('');const pending=useRef(false);async function run(action:()=>Promise<void>){if(pending.current)return;pending.current=true;setBusy(true);setMessage('');try{await action();setMessage('Saved.');reload();}catch(e){setMessage(e instanceof Error?e.message:'Unable to save. Please try again.');}finally{pending.current=false;setBusy(false);}}return {busy,message,run};}
async function rpc(name:string,args:Record<string,unknown>){if(!supabase)throw Error('Connection unavailable');const {data,error}=await supabase.rpc(name,args);if(error)throw Error(error.code==='42501'?'Commissioner access required.':error.code==='P0001'?error.message:'Unable to save. Please try again.');return data;}
export function Admin({data,reload}:{data:PageData;reload:()=>void}){
 const {busy,message,run}=useAction(reload);const [invite,setInvite]=useState('');
 const setting=(key:string)=>String(data.settings.find(s=>s.key===key)?.valueJson??'');
 return <><PageHeader eyebrow="Commissioner" title="Admin"/>{message&&<p role="status" className="mt-4 border border-line-sheet p-4">{message}</p>}
 <Section title="Commissioner tools"><div className="flex flex-wrap gap-5"><Link href="/admin/recaps" className="text-kelly underline">Write and publish recaps</Link><Link href="/admin/recaps/voice" className="text-kelly underline">Recap voice notes</Link><a href="https://github.com/Chilldebrand/HallofBlamers/actions/workflows/espn-sync.yml" target="_blank" rel="noreferrer" className="text-kelly underline">Run a refresh in GitHub ↗</a></div></Section>
 <Section title="Draft date"><form onSubmit={e=>{e.preventDefault();const value=new FormData(e.currentTarget).get('date');void run(async()=>{await rpc('hob_save_setting',{setting_key:'draft_date',setting_value:value});});}} className="flex flex-wrap items-end gap-3"><label>Draft date<input name="date" aria-label="Draft date" type="date" required defaultValue={setting('draft_date')} className={inputClass}/></label><button disabled={busy} className={buttonClass}>Save date</button></form></Section>
 <Section title="Managers and invitations">{invite&&<div className="mb-5 border border-kelly p-4"><p className="text-sm">Invitation created. Copy this link for the manager; it expires in seven days. No email was sent.</p><input aria-label="Invitation link" readOnly value={invite} className={inputClass}/></div>}<GridTable head={['Manager','Franchise','Role','Access','Action']} rows={data.managers.map(m=>{const membership=data.memberships.find(s=>s.managerId===m.id),active=membership&&membership.revokedAt===null;return [m.name,m.franchiseId?name(data,m.franchiseId):'Unassigned',m.role,active?'Active':membership?'Revoked':'Not joined',m.id===data.shell.viewer.managerId?'You':<button key={m.id} disabled={busy} className="text-kelly underline disabled:opacity-50" onClick={()=>void run(async()=>{if(active){await rpc('hob_revoke_member',{target_manager_id:m.id});}else{const token=await rpc('hob_create_invite',{target_manager_id:m.id});setInvite(`${window.location.origin}${window.location.pathname}#/join?token=${encodeURIComponent(token)}`);}})}>{active?'Revoke access':'Create invite'}</button>];})}/>
 <form className="mt-5 flex flex-wrap items-end gap-3" onSubmit={e=>{e.preventDefault();const form=e.currentTarget;const f=new FormData(form);void run(async()=>{await rpc('hob_add_manager',{manager_name:String(f.get('name')),franchise:f.get('franchise')?Number(f.get('franchise')):null});form.reset();});}}><label>Name<input name="name" required maxLength={100} className={inputClass}/></label><label>Franchise<select name="franchise" className={inputClass}><option value="">Unassigned</option>{data.franchises.map(f=><option key={f.id} value={f.id}>{f.canonicalName}</option>)}</select></label><button disabled={busy} className={buttonClass}>Add manager</button></form></Section>
 <Section title="Recent refreshes"><GridTable head={['Started','Scope','Status','Views','New snapshots']} rows={data.syncRuns.map(r=>[new Date(r.startedAt).toLocaleString(),r.tier,r.status,r.viewsFetched,r.snapshotsNew])}/></Section><Section title="Statistics builds"><GridTable head={['Build','Started','Status','Duration']} rows={data.statBuilds.map(r=>[r.id,new Date(r.startedAt).toLocaleString(),r.status,r.durationMs===null?'—':`${r.durationMs} ms`])}/></Section></>;
}
export function RecapAdmin({data,id,voice,reload}:{data:PageData;id:number|null;voice:boolean;reload:()=>void}){
 const navigate=useNavigate();const {busy,message,run}=useAction(reload);
 const recap=data.recaps.find(r=>r.id===id);
 const [markdown,setMarkdown]=useState(recap?.markdownDraft??'');
 const [version,setVersion]=useState({markdown:recap?.markdownDraft??null,status:recap?.status??'draft'});
 async function save(operation:string){if(!recap)return;await rpc('hob_save_recap',{recap_id:recap.id,recap_season:recap.season,recap_week:recap.week,markdown,expected_markdown:version.markdown,expected_status:version.status,operation});setVersion({markdown,status:operation==='publish'?'published':'edited'});}
 function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);void run(async()=>{const saved=await rpc('hob_save_recap',{recap_id:null,recap_season:Number(f.get('season')),recap_week:Number(f.get('week')),markdown:'',expected_markdown:null,expected_status:null,operation:'save'});navigate(`/admin/recaps/${saved}`);});}
 return <><PageHeader eyebrow="Commissioner" title={voice?'Recap Voice':id?'Edit Recap':'Weekly Recaps'}/><Link href="/admin" className="mt-4 block text-kelly">← Admin</Link>{message&&<p role="status" className="mt-4 border border-line-sheet p-4">{message}</p>}{voice?<Section title="Voice notes"><p className="mb-4 text-sm text-muted">Save editorial guidance for your recaps. Automatic AI generation remains disabled.</p><form onSubmit={e=>{e.preventDefault();const value=new FormData(e.currentTarget).get('notes');void run(async()=>{await rpc('hob_save_setting',{setting_key:'recap_voice_notes',setting_value:value});});}}><label>Notes<textarea name="notes" defaultValue={String(data.settings.find(s=>s.key==='recap_voice_notes')?.valueJson??'')} rows={10} maxLength={12000} className={inputClass}/></label><button disabled={busy} className={buttonClass}>Save notes</button></form></Section>:id?recap?<><Section title={`${recap.season} · Week ${recap.week} · ${version.status}`}><label>Recap text (Markdown)<textarea aria-label="Recap text" value={markdown} onChange={e=>setMarkdown(e.target.value)} maxLength={100000} rows={16} className={inputClass}/></label><div className="mt-4 flex flex-wrap gap-3"><button disabled={busy} className={buttonClass} onClick={()=>void run(()=>save('save'))}>Save draft</button><button disabled={busy||!markdown.trim()} className={buttonClass} onClick={()=>void run(()=>save('publish'))}>Publish recap</button>{version.status==='published'&&<button disabled={busy} className={buttonClass} onClick={()=>void run(()=>save('unpublish'))}>Unpublish</button>}</div></Section><Section title="Preview"><RecapMarkdownView markdown={markdown}/></Section></>:<Empty>Recap not found.</Empty>:<><Section title="Drafts and published recaps"><GridTable head={['Season','Week','Status','Edit']} rows={data.recaps.map(r=>[r.season,r.week,r.status,<Link key={r.id} href={`/admin/recaps/${r.id}`} className="text-kelly underline">Edit</Link>])}/></Section><Section title="Create a weekly recap"><form onSubmit={create} className="flex flex-wrap items-end gap-3"><label>Season<select name="season" defaultValue={data.season} className={inputClass}>{data.seasons.map(s=><option key={s.season}>{s.season}</option>)}</select></label><label>Week<input name="week" type="number" min={1} max={25} defaultValue={data.week} required className={inputClass}/></label><button disabled={busy} className={buttonClass}>Create draft</button></form></Section></>}</>;
}
