import {EloChart} from '../../../src/components/history/EloChart';
import {buildEloSeries,markSeasonEndDots} from '../../../src/shared/elo-series';
import type {PageData} from '../api/pages';
import Link from '../components/Link';
import {Empty,Franchise,GridTable,label,name,number,PageHeader,Section,SeasonLinks} from './LeagueParts';
import {RECORD_KEY_META} from '../../../src/shared/records';
import type {RecordKey} from '../../../src/engines';
import {GameCards} from './Matchups';

export function History(){return <><PageHeader eyebrow="The Archive" title="History"/><div className="mt-6 grid gap-4 sm:grid-cols-2">{[['franchises','Every franchise, active and departed.'],['records','League bests and worsts, all time.'],['h2h','Franchise vs. franchise, all time.'],['seasons','Every season, year by year.'],['belt','The full lineage, reign by reign.'],['timeline',"The league’s story, in order."],['transactions','Trades, waivers, and roster moves.'],['what-if','Replay schedules and optimal lineups.']].map(([key,description])=><Link key={key} href={'/'+key} className="border border-line-sheet p-5 hover:border-kelly"><h2 className="display text-xl text-ink">{key==='h2h'?'Head-to-Head':label(key)}</h2><p className="mt-2 text-sm text-muted">{description}</p></Link>)}</div></>;}

export function Records({data,embedded=false}:{data:PageData;embedded?:boolean}){const keys=[...new Set(data.records.map(r=>r.recordKey))];return <>{!embedded&&<PageHeader eyebrow="The Archive" title="Record Book"/>}{keys.length?keys.map(key=><Section key={key} title={RECORD_KEY_META[key as RecordKey]?.label??label(key)}><GridTable head={['Rank','Franchise','Value','Season','Week']} rows={data.records.filter(r=>r.recordKey===key).map(r=>[r.rank,<Franchise key={r.id} data={data} id={r.franchiseId}/>,RECORD_KEY_META[key as RecordKey]?.format(r.value)??number(r.value),<Link key="year" href={`/seasons/${r.season}`}>{r.season}</Link>,r.week?<Link key="week" href={`/matchups/${r.season}/${r.week}`}>W{r.week}</Link>:'Season'])}/></Section>):<Empty/>}</>;}

export function Belt({data,embedded=false}:{data:PageData;embedded?:boolean}){const current=data.beltReigns.find(r=>r.isCurrent);return <>{!embedded&&<><PageHeader eyebrow="Championship lineage" title="The Belt"/><Section title="Current holder">{current?<div className="border-l-4 border-gold-fill bg-sheet-raised p-6"><Franchise data={data} id={current.franchiseId}/><p className="mt-4">Reign #{current.reignNo} · {current.defenses} defenses · {current.weeksHeld} weeks held</p><p className="mt-2 text-sm text-muted">Since {current.startSeason} Week {current.startWeek}</p></div>:<Empty>The belt is currently vacant.</Empty>}</Section></>}
 <Section title="Reign history"><GridTable head={['Reign','Holder','From','Through','Defenses','Weeks','Ended']} rows={data.beltReigns.map(r=>[r.reignNo,<Franchise key={r.id} data={data} id={r.franchiseId}/>,`${r.startSeason} W${r.startWeek}`,r.isCurrent?'Current':`${r.endSeason} W${r.endWeek}`,r.defenses,r.weeksHeld,r.endReason??'—'])}/></Section>{!embedded&&<Section title="Title matches"><GridTable head={['Week','Holder','Challenger','Score','Result']} rows={data.beltMatches.map(m=>[<Link key={m.id} href={`/matchups/${m.season}/${m.week}/${m.matchupId}`}>{m.season} W{m.week}</Link>,<Franchise key="h" data={data} id={m.holderFranchiseId}/>,<Franchise key="a" data={data} id={m.challengerFranchiseId}/>,`${number(m.holderScore)}–${number(m.challengerScore)}`,label(m.result)])}/></Section>}</>;}

export function Franchises({data,id}:{data:PageData;id:number|null}){
 if(id===null)return <><PageHeader eyebrow="The Archive" title="Franchises"/><Section title="All-time standings"><GridTable head={['Franchise','Status','Seasons','W–L–T','Titles','Elo']} rows={data.franchises.map(f=>{const c=data.careerStats.find(r=>r.franchiseId===f.id);return [<Franchise key={f.id} data={data} id={f.id}/>,f.active?'Active':'Departed',c?.seasons??0,c?`${c.wins}–${c.losses}–${c.ties}`:'—',c?.championships??'—',number(c?.currentElo,0)];})}/></Section></>;
 const f=data.franchises.find(r=>r.id===id),c=data.careerStats.find(r=>r.franchiseId===id);
 const series=buildEloSeries(data.eloHistory);
 series.points=markSeasonEndDots(series.points,new Set(data.seasonStats.filter(s=>s.champion).map(s=>s.season)),new Set(data.seasonStats.filter(s=>s.sacko).map(s=>s.season)));
 if(!f)return <Empty>Franchise not found.</Empty>;
 return <><Link href="/franchises" className="text-kelly">← Franchises</Link><PageHeader eyebrow={`${f.joinedSeason}–${f.departedSeason??'present'} · ${f.managerName}`} title={f.canonicalName}/>{c&&<div className="my-6 grid grid-cols-2 gap-4 md:grid-cols-4">{[['Record',`${c.wins}–${c.losses}–${c.ties}`],['Titles',c.championships],['Points',number(c.pointsFor)],['Elo',number(c.currentElo,0)]].map(([k,v])=><div key={k} className="border border-line-sheet bg-sheet-raised p-4"><p className="display text-xs tracking-wide text-muted">{k}</p><p className="mt-2 text-2xl tabular-nums">{v}</p></div>)}</div>}
 <Section title="Season history"><SeasonStats data={data}/></Section>
 <Section title="Elo history"><EloChart series={series}/></Section>
 <Section title="Trophy case">{data.achievements.length?<div className="grid gap-3 sm:grid-cols-2">{data.achievements.map(a=><div key={a.id} className="border border-line-sheet p-4"><h3 className="display text-lg">{label(a.achievementKey)}</h3><p className="text-sm text-muted">{a.season} · Week {a.week}</p></div>)}</div>:<Empty>No achievements recorded yet.</Empty>}</Section>
 <Section title="Head-to-head"><H2HTable data={data}/></Section><Belt data={data} embedded/><Records data={data} embedded/></>;
}

export function SeasonStats({data}:{data:PageData}){return <GridTable head={['Season','Franchise','W–L–T','PF','PA','Finish','Honors']} rows={data.seasonStats.map(r=>[<Link key="year" href={`/seasons/${r.season}`}>{r.season}</Link>,<Franchise key={r.id} data={data} id={r.franchiseId}/>,`${r.wins}–${r.losses}–${r.ties}`,number(r.pointsFor),number(r.pointsAgainst),r.finalStanding&&r.finalStanding>0?r.finalStanding:'—',r.champion?'Champion':r.sacko?'Sacko':r.madePlayoffs?'Playoffs':'—'])}/>;}
export function Seasons({data,detail}:{data:PageData;detail:boolean}){return <><PageHeader eyebrow="The Archive" title={detail?`${data.season} Season`:'Seasons'}/><SeasonLinks data={data} path="seasons"/>{detail?<><Section title="Season results"><SeasonStats data={data}/></Section><Section title="Weeks"><div className="flex flex-wrap gap-3">{data.weeks.map(w=><Link key={w.week} href={`/matchups/${data.season}/${w.week}`} className="border border-line-sheet p-3 text-kelly">Week {w.week}</Link>)}</div></Section><Section title="Draft"><GridTable head={['Pick','Round','Franchise','Player']} rows={data.draftPicks.map(p=>[p.overallPick,p.round,<Franchise key={p.id} data={data} id={data.teamSeasons.find(t=>t.id===p.teamSeasonId)?.franchiseId??null}/>,data.players.find(r=>r.espnPlayerId===p.playerId)?.fullName??`Player ${p.playerId}`])}/></Section></>:<div className="grid gap-4 sm:grid-cols-2">{data.seasons.map(s=><Link key={s.season} href={`/seasons/${s.season}`} className="border border-line-sheet p-5"><h2 className="display text-3xl text-kelly">{s.season}</h2><p className="mt-2 text-sm">{s.teamCount} franchises · {s.status}</p><p className="mt-2">{data.seasonStats.find(r=>r.season===s.season&&r.champion)?`Champion: ${name(data,data.seasonStats.find(r=>r.season===s.season&&r.champion)!.franchiseId)}`:'Champion not decided'}</p></Link>)}</div>}</>;}

function H2HTable({data}:{data:PageData}){return <GridTable head={['Franchise A','Franchise B','Regular W–L–T (A)','Playoffs W–L–T (A)','Details']} rows={data.h2hPairs.map(p=>[<Franchise key="a" data={data} id={p.franchiseA}/>,<Franchise key="b" data={data} id={p.franchiseB}/>,`${p.regW}–${p.regL}–${p.regT}`,`${p.playoffW}–${p.playoffL}–${p.playoffT}`,<Link key={p.id} href={`/h2h/${p.franchiseA}/${p.franchiseB}`} className="text-kelly">Game log →</Link>])}/>;}
export function H2H({data,a,b}:{data:PageData;a:number|null;b:number|null}){
 const pairs=a===null?data.h2hPairs:data.h2hPairs.filter(p=>(p.franchiseA===a&&p.franchiseB===b)||(p.franchiseA===b&&p.franchiseB===a));
 const games=data.matchups.filter(m=>{const x=data.teamSeasons.find(t=>t.id===m.homeTeamSeasonId)?.franchiseId,y=data.teamSeasons.find(t=>t.id===m.awayTeamSeasonId)?.franchiseId;return(x===a&&y===b)||(x===b&&y===a);});
 return <><PageHeader eyebrow="The Archive" title="Head-to-Head"/><Section title={a===null?'All matchups':`${name(data,a)} vs. ${name(data,b)}`}><H2HTable data={{...data,h2hPairs:pairs}}/></Section>{a!==null&&<Section title="Game log"><GameCards data={{...data,matchups:games}}/></Section>}</>;
}

