-- Generated by migration/postgres-schema.ts from the checked-in SQLite schema.

-- All source tables remain private; later reviewed RPCs expose only allowed fields.

CREATE SCHEMA hob_private;

REVOKE ALL ON SCHEMA hob_private FROM PUBLIC;

CREATE TABLE hob_private.import_marker (source_hash text PRIMARY KEY, imported_at timestamptz NOT NULL DEFAULT now());

ALTER TABLE hob_private.import_marker ENABLE ROW LEVEL SECURITY;

CREATE TABLE hob_private."achievements" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "build_id" integer NOT NULL,
  "achievement_key" text NOT NULL,
  "franchise_id" integer NOT NULL,
  "season" integer NOT NULL,
  "week" integer NOT NULL,
  "dedupe_key" text NOT NULL,
  "payload_json" jsonb,
  UNIQUE ("dedupe_key")
);

ALTER TABLE hob_private."achievements" ENABLE ROW LEVEL SECURITY;

CREATE TABLE hob_private."allplay_week" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "build_id" integer NOT NULL,
  "season" integer NOT NULL,
  "week" integer NOT NULL,
  "franchise_id" integer NOT NULL,
  "wins" integer NOT NULL,
  "losses" integer NOT NULL,
  "ties" integer NOT NULL,
  "luck_score" double precision,
  UNIQUE ("season","week","franchise_id")
);

ALTER TABLE hob_private."allplay_week" ENABLE ROW LEVEL SECURITY;

CREATE TABLE hob_private."app_settings" (
  "key" text PRIMARY KEY NOT NULL,
  "value_json" jsonb NOT NULL,
  "updated_at" timestamptz NOT NULL
);

ALTER TABLE hob_private."app_settings" ENABLE ROW LEVEL SECURITY;

CREATE TABLE hob_private."belt_matches" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "build_id" integer NOT NULL,
  "matchup_id" integer NOT NULL,
  "season" integer NOT NULL,
  "week" integer NOT NULL,
  "holder_franchise_id" integer NOT NULL,
  "challenger_franchise_id" integer NOT NULL,
  "result" text NOT NULL CHECK ("result" IN ('defense','transfer')),
  "holder_score" double precision NOT NULL,
  "challenger_score" double precision NOT NULL,
  UNIQUE ("matchup_id")
);

ALTER TABLE hob_private."belt_matches" ENABLE ROW LEVEL SECURITY;

CREATE TABLE hob_private."belt_reigns" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "build_id" integer NOT NULL,
  "reign_no" integer NOT NULL,
  "franchise_id" integer NOT NULL,
  "won_from_franchise_id" integer,
  "start_season" integer NOT NULL,
  "start_week" integer NOT NULL,
  "end_season" integer,
  "end_week" integer,
  "defenses" integer NOT NULL,
  "weeks_held" integer NOT NULL,
  "end_reason" text CHECK ("end_reason" IN ('lost','vacated','override')),
  "is_current" boolean NOT NULL,
  UNIQUE ("reign_no")
);

ALTER TABLE hob_private."belt_reigns" ENABLE ROW LEVEL SECURITY;

CREATE TABLE hob_private."career_stats" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "build_id" integer NOT NULL,
  "franchise_id" integer NOT NULL,
  "seasons" integer NOT NULL,
  "wins" integer NOT NULL,
  "losses" integer NOT NULL,
  "ties" integer NOT NULL,
  "win_pct" double precision NOT NULL,
  "points_for" double precision NOT NULL,
  "points_against" double precision NOT NULL,
  "allplay_w" integer NOT NULL,
  "allplay_l" integer NOT NULL,
  "allplay_t" integer NOT NULL,
  "championships" integer NOT NULL,
  "sackos" integer NOT NULL,
  "playoff_appearances" integer NOT NULL,
  "best_finish" integer,
  "worst_finish" integer,
  "highest_week" double precision,
  "highest_week_season" integer,
  "highest_week_week" integer,
  "lowest_week" double precision,
  "lowest_week_season" integer,
  "lowest_week_week" integer,
  "longest_win_streak" integer,
  "longest_win_streak_start_season" integer,
  "longest_win_streak_start_week" integer,
  "longest_win_streak_end_season" integer,
  "longest_win_streak_end_week" integer,
  "longest_loss_streak" integer,
  "longest_loss_streak_start_season" integer,
  "longest_loss_streak_start_week" integer,
  "longest_loss_streak_end_season" integer,
  "longest_loss_streak_end_week" integer,
  "current_elo" double precision NOT NULL,
  "peak_elo" double precision NOT NULL,
  "luck_total" double precision,
  "expected_wins" double precision,
  "efficiency_avg" double precision,
  "beatdowns" integer NOT NULL DEFAULT 0,
  "worst_beatdown_margin" double precision,
  "worst_beatdown_season" integer,
  "worst_beatdown_week" integer,
  UNIQUE ("franchise_id")
);

ALTER TABLE hob_private."career_stats" ENABLE ROW LEVEL SECURITY;

CREATE TABLE hob_private."chat_messages" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "channel" text NOT NULL,
  "manager_id" integer,
  "kind" text NOT NULL DEFAULT 'user' CHECK ("kind" IN ('user','system')),
  "body" text NOT NULL,
  "dedupe_key" text UNIQUE,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  CHECK ((kind = 'user' AND manager_id IS NOT NULL) OR (kind = 'system' AND manager_id IS NULL)),
  CHECK (length(body) <= 2000)
);

ALTER TABLE hob_private."chat_messages" ENABLE ROW LEVEL SECURITY;

CREATE TABLE hob_private."context_notes" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "build_id" integer NOT NULL,
  "subject_type" text NOT NULL CHECK ("subject_type" IN ('team_week','matchup')),
  "season" integer NOT NULL,
  "week" integer NOT NULL,
  "franchise_id" integer,
  "matchup_id" integer,
  "rule_id" text NOT NULL,
  "salience" integer NOT NULL,
  "rendered_text" text NOT NULL,
  "facts_json" jsonb
);

ALTER TABLE hob_private."context_notes" ENABLE ROW LEVEL SECURITY;

CREATE TABLE hob_private."corrections" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "target_table" text NOT NULL,
  "target_key_json" jsonb NOT NULL,
  "field" text NOT NULL,
  "value_json" jsonb NOT NULL,
  "reason" text NOT NULL,
  "created_by" text NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "active" boolean NOT NULL DEFAULT true
);

ALTER TABLE hob_private."corrections" ENABLE ROW LEVEL SECURITY;

CREATE TABLE hob_private."draft_grades" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "build_id" integer NOT NULL,
  "season" integer NOT NULL,
  "franchise_id" integer NOT NULL,
  "pick_count" integer NOT NULL,
  "total_value" double precision NOT NULL,
  "avg_reach_steal_score" double precision NOT NULL,
  "avg_reach_steal_pct" double precision NOT NULL,
  "z_score" double precision NOT NULL,
  "grade" text NOT NULL CHECK ("grade" IN ('A','B','C','D','F')),
  UNIQUE ("season","franchise_id")
);

ALTER TABLE hob_private."draft_grades" ENABLE ROW LEVEL SECURITY;

CREATE TABLE hob_private."draft_pick_values" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "build_id" integer NOT NULL,
  "season" integer NOT NULL,
  "draft_pick_id" integer NOT NULL,
  "franchise_id" integer NOT NULL,
  "team_season_id" integer NOT NULL,
  "player_id" integer NOT NULL,
  "round" integer NOT NULL,
  "round_pick" integer NOT NULL,
  "overall_pick" integer NOT NULL,
  "value" double precision NOT NULL,
  "value_rank" integer NOT NULL,
  "total_ranked_picks" integer NOT NULL,
  "reach_steal_score" integer NOT NULL,
  "reach_steal_pct" double precision NOT NULL,
  UNIQUE ("draft_pick_id")
);

ALTER TABLE hob_private."draft_pick_values" ENABLE ROW LEVEL SECURITY;

CREATE TABLE hob_private."draft_picks" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "season" integer NOT NULL,
  "round" integer NOT NULL,
  "round_pick" integer NOT NULL,
  "overall_pick" integer NOT NULL,
  "team_season_id" integer NOT NULL,
  "player_id" integer NOT NULL,
  "keeper" boolean NOT NULL DEFAULT false,
  "auction_amount" double precision,
  UNIQUE ("season","overall_pick")
);

ALTER TABLE hob_private."draft_picks" ENABLE ROW LEVEL SECURITY;

CREATE TABLE hob_private."elo_history" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "build_id" integer NOT NULL,
  "season" integer NOT NULL,
  "week" integer NOT NULL,
  "franchise_id" integer NOT NULL,
  "elo_pre" double precision NOT NULL,
  "elo_post" double precision NOT NULL,
  UNIQUE ("season","week","franchise_id")
);

ALTER TABLE hob_private."elo_history" ENABLE ROW LEVEL SECURITY;

CREATE TABLE hob_private."events" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "event_type" text NOT NULL,
  "season" integer,
  "week" integer,
  "occurred_at" timestamptz NOT NULL,
  "detected_at" timestamptz NOT NULL,
  "franchise_id" integer,
  "matchup_id" integer,
  "player_id" integer,
  "payload_json" jsonb NOT NULL,
  "dedupe_key" text NOT NULL UNIQUE
);

ALTER TABLE hob_private."events" ENABLE ROW LEVEL SECURITY;

CREATE TABLE hob_private."franchise_elo" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "build_id" integer NOT NULL,
  "franchise_id" integer NOT NULL,
  "current" double precision NOT NULL,
  "peak" double precision NOT NULL,
  "peak_season" integer NOT NULL,
  "peak_week" integer NOT NULL,
  "trough" double precision NOT NULL,
  "weeks_at_no1" integer NOT NULL,
  UNIQUE ("franchise_id")
);

ALTER TABLE hob_private."franchise_elo" ENABLE ROW LEVEL SECURITY;

CREATE TABLE hob_private."franchise_managers" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "franchise_id" integer NOT NULL,
  "manager_name" text NOT NULL,
  "espn_owner_swid" text,
  "from_season" integer NOT NULL,
  "to_season" integer
);

ALTER TABLE hob_private."franchise_managers" ENABLE ROW LEVEL SECURITY;

CREATE TABLE hob_private."franchises" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "canonical_name" text NOT NULL,
  "manager_name" text NOT NULL,
  "joined_season" integer NOT NULL,
  "departed_season" integer,
  "active" boolean NOT NULL DEFAULT true,
  "accent_color" text,
  "notes" text
);

ALTER TABLE hob_private."franchises" ENABLE ROW LEVEL SECURITY;

CREATE TABLE hob_private."h2h_pairs" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "build_id" integer NOT NULL,
  "franchise_a" integer NOT NULL,
  "franchise_b" integer NOT NULL,
  "reg_w" integer NOT NULL,
  "reg_l" integer NOT NULL,
  "reg_t" integer NOT NULL,
  "playoff_w" integer NOT NULL,
  "playoff_l" integer NOT NULL,
  "playoff_t" integer NOT NULL,
  "points_a" double precision NOT NULL,
  "points_b" double precision NOT NULL,
  "avg_margin" double precision NOT NULL,
  "streak_holder" integer,
  "streak_len" integer NOT NULL,
  "largest_win_json" jsonb,
  "closest_game_json" jsonb,
  "last_meeting_json" jsonb,
  UNIQUE ("franchise_a","franchise_b")
);

ALTER TABLE hob_private."h2h_pairs" ENABLE ROW LEVEL SECURITY;

CREATE TABLE hob_private."leagues" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "espn_league_id" integer NOT NULL UNIQUE,
  "name" text NOT NULL,
  "first_season" integer NOT NULL
);

ALTER TABLE hob_private."leagues" ENABLE ROW LEVEL SECURITY;

CREATE TABLE hob_private."managers" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" text NOT NULL,
  "franchise_id" integer,
  "role" text NOT NULL CHECK ("role" IN ('commissioner','manager')),
  "invite_token" text NOT NULL UNIQUE,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "pin_hash" text,
  "pin_failed_attempts" integer NOT NULL DEFAULT 0,
  "pin_lockout_level" integer NOT NULL DEFAULT 0,
  "pin_locked_until" integer
);

ALTER TABLE hob_private."managers" ENABLE ROW LEVEL SECURITY;

CREATE TABLE hob_private."matchups" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "season" integer NOT NULL,
  "week" integer NOT NULL,
  "espn_matchup_id" integer NOT NULL,
  "home_team_season_id" integer NOT NULL,
  "away_team_season_id" integer,
  "home_score" double precision NOT NULL,
  "away_score" double precision NOT NULL,
  "home_projected" double precision,
  "away_projected" double precision,
  "playoff_tier" text,
  "multi_week_group" text,
  "is_final" boolean NOT NULL,
  "winner" text CHECK ("winner" IN ('home','away','tie')),
  UNIQUE ("season","week","espn_matchup_id")
);

ALTER TABLE hob_private."matchups" ENABLE ROW LEVEL SECURITY;

CREATE TABLE hob_private."notification_prefs" (
  "manager_id" integer PRIMARY KEY NOT NULL,
  "lead_changes" boolean NOT NULL DEFAULT false,
  "finals" boolean NOT NULL DEFAULT true,
  "records" boolean NOT NULL DEFAULT true,
  "belt_events" boolean NOT NULL DEFAULT true,
  "lineup_holes" boolean NOT NULL DEFAULT true,
  "weekly_recap" boolean NOT NULL DEFAULT true,
  "updated_at" timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE hob_private."notification_prefs" ENABLE ROW LEVEL SECURITY;

CREATE TABLE hob_private."pickem_picks" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "manager_id" integer,
  "is_algorithm" boolean NOT NULL DEFAULT false,
  "season" integer NOT NULL,
  "week" integer NOT NULL,
  "matchup_id" integer NOT NULL,
  "picked_franchise_id" integer NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  UNIQUE ("manager_id","matchup_id")
);

ALTER TABLE hob_private."pickem_picks" ENABLE ROW LEVEL SECURITY;

CREATE TABLE hob_private."players" (
  "espn_player_id" integer PRIMARY KEY NOT NULL,
  "full_name" text NOT NULL,
  "default_position" text NOT NULL,
  "pro_team" text,
  "headshot_url" text
);

ALTER TABLE hob_private."players" ENABLE ROW LEVEL SECURITY;

CREATE TABLE hob_private."playoff_odds" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "build_id" integer NOT NULL,
  "season" integer NOT NULL,
  "franchise_id" integer NOT NULL,
  "playoff_probability" double precision NOT NULL,
  "top_seed_probability" double precision NOT NULL,
  "seed_distribution_json" jsonb NOT NULL,
  "runs" integer NOT NULL,
  UNIQUE ("franchise_id")
);

ALTER TABLE hob_private."playoff_odds" ENABLE ROW LEVEL SECURITY;

CREATE TABLE hob_private."podcast_episodes" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "season" integer NOT NULL,
  "week" integer NOT NULL,
  "status" text NOT NULL CHECK ("status" IN ('draft','edited','published')),
  "facts_json" jsonb NOT NULL,
  "prompt_version" text,
  "model" text,
  "segments_draft" jsonb NOT NULL,
  "segments_final" jsonb,
  "segments_generated" jsonb NOT NULL,
  "tokens_in" integer,
  "tokens_out" integer,
  "cost_usd" double precision,
  "created_at" timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE hob_private."podcast_episodes" ENABLE ROW LEVEL SECURITY;

CREATE TABLE hob_private."poll_options" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "poll_id" integer NOT NULL,
  "label" text NOT NULL,
  "sort" integer NOT NULL,
  "is_write_in" boolean NOT NULL DEFAULT false
);

ALTER TABLE hob_private."poll_options" ENABLE ROW LEVEL SECURITY;

CREATE TABLE hob_private."poll_votes" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "poll_id" integer NOT NULL,
  "option_id" integer NOT NULL,
  "manager_id" integer NOT NULL,
  "voted_at" timestamptz NOT NULL DEFAULT now(),
  UNIQUE ("poll_id","option_id","manager_id")
);

ALTER TABLE hob_private."poll_votes" ENABLE ROW LEVEL SECURITY;

CREATE TABLE hob_private."polls" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "question" text NOT NULL,
  "description" text,
  "kind" text NOT NULL CHECK ("kind" IN ('single','multi')),
  "status" text NOT NULL CHECK ("status" IN ('draft','open','closed')),
  "anonymous" boolean NOT NULL DEFAULT false,
  "allow_write_in" boolean NOT NULL DEFAULT false,
  "created_by" integer NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "opens_at" timestamptz,
  "closes_at" timestamptz
);

ALTER TABLE hob_private."polls" ENABLE ROW LEVEL SECURITY;

CREATE TABLE hob_private."predictions" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "manager_id" integer NOT NULL,
  "season" integer NOT NULL,
  "category" text NOT NULL CHECK ("category" IN ('champion','sacko','top_scorer','win_total','bold_take')),
  "subject" text NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  UNIQUE ("manager_id","season","category")
);

ALTER TABLE hob_private."predictions" ENABLE ROW LEVEL SECURITY;

CREATE TABLE hob_private."preview_episodes" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "season" integer NOT NULL,
  "week" integer NOT NULL,
  "status" text NOT NULL CHECK ("status" IN ('draft','edited','published')),
  "facts_json" jsonb NOT NULL,
  "prompt_version" text,
  "model" text,
  "segments_draft" jsonb NOT NULL,
  "segments_final" jsonb,
  "segments_generated" jsonb NOT NULL,
  "tokens_in" integer,
  "tokens_out" integer,
  "cost_usd" double precision,
  "created_at" timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE hob_private."preview_episodes" ENABLE ROW LEVEL SECURITY;

CREATE TABLE hob_private."push_subscriptions" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "manager_id" integer NOT NULL,
  "endpoint" text NOT NULL UNIQUE,
  "p256dh" text NOT NULL,
  "auth" text NOT NULL,
  "user_agent" text,
  "last_delivered_event_id" integer NOT NULL DEFAULT 0,
  "created_at" timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE hob_private."push_subscriptions" ENABLE ROW LEVEL SECURITY;

CREATE TABLE hob_private."recap_exemplars" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "recap_id" integer NOT NULL UNIQUE,
  "season" integer NOT NULL,
  "week" integer NOT NULL,
  "style" text NOT NULL,
  "draft_md" text NOT NULL,
  "published_md" text NOT NULL,
  "captured_at" timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE hob_private."recap_exemplars" ENABLE ROW LEVEL SECURITY;

CREATE TABLE hob_private."recap_style_guides" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "guide_text" text NOT NULL,
  "exemplar_count" integer NOT NULL,
  "source_recap_ids" jsonb NOT NULL,
  "model" text,
  "tokens_in" integer,
  "tokens_out" integer,
  "cost_usd" double precision,
  "is_active" boolean NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE hob_private."recap_style_guides" ENABLE ROW LEVEL SECURITY;

CREATE TABLE hob_private."recaps" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "season" integer NOT NULL,
  "week" integer NOT NULL,
  "style" text NOT NULL,
  "status" text NOT NULL CHECK ("status" IN ('draft','edited','published')),
  "facts_json" jsonb NOT NULL,
  "prompt_version" text,
  "model" text,
  "markdown_draft" text,
  "markdown_final" text,
  "markdown_generated" text,
  "tokens_in" integer,
  "tokens_out" integer,
  "cost_usd" double precision,
  "created_at" timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE hob_private."recaps" ENABLE ROW LEVEL SECURITY;

CREATE TABLE hob_private."record_entries" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "build_id" integer NOT NULL,
  "record_key" text NOT NULL,
  "rank" integer NOT NULL,
  "franchise_id" integer NOT NULL,
  "season" integer NOT NULL,
  "week" integer,
  "value" double precision NOT NULL,
  "week_type" text CHECK ("week_type" IN ('regular','playoff','consolation','championship')),
  "detail_json" jsonb,
  UNIQUE ("record_key","rank","franchise_id","season","week")
);

ALTER TABLE hob_private."record_entries" ENABLE ROW LEVEL SECURITY;

CREATE TABLE hob_private."revenge_events" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "build_id" integer NOT NULL,
  "franchise_id" integer NOT NULL,
  "player_id" integer NOT NULL,
  "departure_type" text NOT NULL CHECK ("departure_type" IN ('dropped','traded_away')),
  "departure_transaction_id" integer NOT NULL,
  "departure_espn_tx_id" text NOT NULL,
  "current_franchise_id" integer NOT NULL,
  "current_team_season_id" integer NOT NULL,
  "matchup_id" integer NOT NULL,
  "season" integer NOT NULL,
  "week" integer NOT NULL,
  "points" double precision NOT NULL,
  "is_against_former_franchise" boolean NOT NULL,
  UNIQUE ("franchise_id","player_id","season","week")
);

ALTER TABLE hob_private."revenge_events" ENABLE ROW LEVEL SECURITY;

CREATE TABLE hob_private."roster_slots" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "season" integer NOT NULL,
  "week" integer NOT NULL,
  "team_season_id" integer NOT NULL,
  "player_id" integer NOT NULL,
  "lineup_slot" text NOT NULL,
  "is_starter" boolean NOT NULL,
  "points" double precision,
  "projected_points" double precision,
  "eligible_slots_json" jsonb NOT NULL,
  UNIQUE ("season","week","team_season_id","player_id")
);

ALTER TABLE hob_private."roster_slots" ENABLE ROW LEVEL SECURITY;

CREATE TABLE hob_private."season_stats" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "build_id" integer NOT NULL,
  "season" integer NOT NULL,
  "franchise_id" integer NOT NULL,
  "wins" integer NOT NULL,
  "losses" integer NOT NULL,
  "ties" integer NOT NULL,
  "points_for" double precision NOT NULL,
  "points_against" double precision NOT NULL,
  "allplay_w" integer NOT NULL,
  "allplay_l" integer NOT NULL,
  "allplay_t" integer NOT NULL,
  "luck_total" double precision,
  "expected_wins" double precision,
  "efficiency_avg" double precision,
  "final_standing" integer,
  "made_playoffs" boolean NOT NULL,
  "champion" boolean NOT NULL DEFAULT false,
  "sacko" boolean NOT NULL DEFAULT false,
  "beatdowns" integer NOT NULL DEFAULT 0,
  UNIQUE ("season","franchise_id")
);

ALTER TABLE hob_private."season_stats" ENABLE ROW LEVEL SECURITY;

CREATE TABLE hob_private."seasons" (
  "season" integer PRIMARY KEY NOT NULL,
  "league_id" integer NOT NULL,
  "settings_json" jsonb NOT NULL,
  "scoring_json" jsonb NOT NULL,
  "playoff_format_json" jsonb NOT NULL,
  "team_count" integer NOT NULL,
  "reg_season_weeks" integer NOT NULL,
  "status" text NOT NULL CHECK ("status" IN ('upcoming','active','complete'))
);

ALTER TABLE hob_private."seasons" ENABLE ROW LEVEL SECURITY;

CREATE TABLE hob_private."slot_scoring_stats" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "build_id" integer NOT NULL,
  "slot" text NOT NULL,
  "mean" double precision NOT NULL,
  "variance" double precision NOT NULL,
  "sample_size" integer NOT NULL,
  "season_min" integer NOT NULL,
  "season_max" integer NOT NULL,
  UNIQUE ("slot")
);

ALTER TABLE hob_private."slot_scoring_stats" ENABLE ROW LEVEL SECURITY;

CREATE TABLE hob_private."snapshots" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "season" integer NOT NULL,
  "scoring_period" integer,
  "view" text NOT NULL,
  "url" text NOT NULL,
  "fetched_at" timestamptz NOT NULL,
  "http_status" integer NOT NULL,
  "payload" text NOT NULL,
  "payload_hash" text NOT NULL,
  "superseded" boolean NOT NULL DEFAULT false
);

ALTER TABLE hob_private."snapshots" ENABLE ROW LEVEL SECURITY;

CREATE TABLE hob_private."stat_builds" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "started_at" timestamptz NOT NULL,
  "finished_at" timestamptz,
  "input_hash" text NOT NULL,
  "status" text NOT NULL CHECK ("status" IN ('running','ok','failed')),
  "duration_ms" integer,
  "error_text" text
);

ALTER TABLE hob_private."stat_builds" ENABLE ROW LEVEL SECURITY;

CREATE TABLE hob_private."sync_runs" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "started_at" timestamptz NOT NULL,
  "finished_at" timestamptz,
  "tier" text NOT NULL CHECK ("tier" IN ('live','hourly','daily','manual','backfill')),
  "status" text NOT NULL CHECK ("status" IN ('ok','partial','failed','auth_failed','running')),
  "views_fetched" integer NOT NULL DEFAULT 0,
  "snapshots_new" integer NOT NULL DEFAULT 0,
  "events_emitted" integer NOT NULL DEFAULT 0,
  "error_text" text
);

ALTER TABLE hob_private."sync_runs" ENABLE ROW LEVEL SECURITY;

CREATE TABLE hob_private."team_seasons" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "season" integer NOT NULL,
  "franchise_id" integer NOT NULL,
  "espn_team_id" integer NOT NULL,
  "team_name" text NOT NULL,
  "abbrev" text,
  "logo_url" text,
  "division_id" integer,
  "wins" integer NOT NULL,
  "losses" integer NOT NULL,
  "ties" integer NOT NULL,
  "points_for" double precision NOT NULL,
  "points_against" double precision NOT NULL,
  "final_standing" integer,
  "made_playoffs" boolean NOT NULL,
  UNIQUE ("season","espn_team_id")
);

ALTER TABLE hob_private."team_seasons" ENABLE ROW LEVEL SECURITY;

CREATE TABLE hob_private."team_week" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "build_id" integer NOT NULL,
  "season" integer NOT NULL,
  "week" integer NOT NULL,
  "week_type" text NOT NULL CHECK ("week_type" IN ('regular','playoff','consolation','championship')),
  "team_season_id" integer NOT NULL,
  "franchise_id" integer NOT NULL,
  "opponent_franchise_id" integer,
  "matchup_id" integer,
  "score" double precision NOT NULL,
  "projected" double precision,
  "result" text CHECK ("result" IN ('W','L','T')),
  "margin" double precision,
  "optimal_score" double precision,
  "bench_points_left" double precision,
  "efficiency" double precision,
  "eligibility_fallback" boolean NOT NULL DEFAULT false,
  UNIQUE ("season","week","franchise_id")
);

ALTER TABLE hob_private."team_week" ENABLE ROW LEVEL SECURITY;

CREATE TABLE hob_private."trade_ledger" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "build_id" integer NOT NULL,
  "season" integer NOT NULL,
  "transaction_id" integer NOT NULL,
  "espn_tx_id" text NOT NULL,
  "trade_week" integer NOT NULL,
  "receiving_franchise_id" integer NOT NULL,
  "receiving_team_season_id" integer NOT NULL,
  "sending_franchise_id" integer NOT NULL,
  "sending_team_season_id" integer NOT NULL,
  "player_id" integer NOT NULL,
  "weeks_rostered" integer NOT NULL,
  "starts_made" integer NOT NULL,
  "starter_points" double precision NOT NULL,
  "points_per_start" double precision,
  "still_rostered" boolean NOT NULL,
  "dropped_week" integer,
  "source" text NOT NULL DEFAULT 'espn' CHECK ("source" IN ('espn','inferred')),
  UNIQUE ("transaction_id","receiving_team_season_id","player_id")
);

ALTER TABLE hob_private."trade_ledger" ENABLE ROW LEVEL SECURITY;

CREATE TABLE hob_private."transaction_items" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "transaction_id" integer NOT NULL,
  "team_season_id" integer NOT NULL,
  "player_id" integer NOT NULL,
  "action" text NOT NULL CHECK ("action" IN ('add','drop','trade_away','trade_for')),
  "source" text NOT NULL DEFAULT 'espn' CHECK ("source" IN ('espn','inferred'))
);

ALTER TABLE hob_private."transaction_items" ENABLE ROW LEVEL SECURITY;

CREATE TABLE hob_private."transactions" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "season" integer NOT NULL,
  "espn_tx_id" text NOT NULL,
  "type" text NOT NULL CHECK ("type" IN ('waiver','freeagent','trade','drop','lineup')),
  "status" text NOT NULL,
  "bid_amount" double precision,
  "proposed_at" timestamptz,
  "processed_at" timestamptz,
  "raw_json" jsonb NOT NULL,
  UNIQUE ("season","espn_tx_id")
);

ALTER TABLE hob_private."transactions" ENABLE ROW LEVEL SECURITY;

CREATE TABLE hob_private."waiver_acquisitions" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "build_id" integer NOT NULL,
  "season" integer NOT NULL,
  "franchise_id" integer NOT NULL,
  "team_season_id" integer NOT NULL,
  "player_id" integer NOT NULL,
  "type" text NOT NULL CHECK ("type" IN ('waiver','freeagent')),
  "bid_amount" double precision,
  "transaction_id" integer NOT NULL,
  "espn_tx_id" text NOT NULL,
  "acquired_week" integer NOT NULL,
  "dropped_week" integer,
  "still_rostered" boolean NOT NULL,
  "weeks_rostered" integer NOT NULL,
  "starts_made" integer NOT NULL,
  "starter_points" double precision NOT NULL,
  "points_per_start" double precision,
  UNIQUE ("transaction_id","team_season_id","player_id")
);

ALTER TABLE hob_private."waiver_acquisitions" ENABLE ROW LEVEL SECURITY;

CREATE TABLE hob_private."weeks" (
  "season" integer NOT NULL,
  "week" integer NOT NULL,
  "scoring_period_id" integer NOT NULL,
  "week_type" text NOT NULL CHECK ("week_type" IN ('regular','playoff','consolation','championship')),
  "is_complete" boolean NOT NULL,
  PRIMARY KEY ("season","week")
);

ALTER TABLE hob_private."weeks" ENABLE ROW LEVEL SECURITY;

ALTER TABLE hob_private."achievements" ADD FOREIGN KEY ("build_id") REFERENCES hob_private."stat_builds" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "achievements_franchise_id_idx" ON hob_private."achievements" ("franchise_id");

CREATE INDEX "achievements_season_week_idx" ON hob_private."achievements" ("season","week");

CREATE INDEX "achievements_achievement_key_idx" ON hob_private."achievements" ("achievement_key");

ALTER TABLE hob_private."allplay_week" ADD FOREIGN KEY ("build_id") REFERENCES hob_private."stat_builds" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE hob_private."belt_matches" ADD FOREIGN KEY ("build_id") REFERENCES hob_private."stat_builds" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE hob_private."belt_reigns" ADD FOREIGN KEY ("build_id") REFERENCES hob_private."stat_builds" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE hob_private."career_stats" ADD FOREIGN KEY ("build_id") REFERENCES hob_private."stat_builds" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE hob_private."chat_messages" ADD FOREIGN KEY ("manager_id") REFERENCES hob_private."managers" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "chat_messages_channel_id_idx" ON hob_private."chat_messages" ("channel","id");

ALTER TABLE hob_private."context_notes" ADD FOREIGN KEY ("build_id") REFERENCES hob_private."stat_builds" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "context_notes_season_week_idx" ON hob_private."context_notes" ("season","week");

CREATE INDEX "context_notes_matchup_id_idx" ON hob_private."context_notes" ("matchup_id");

CREATE INDEX "context_notes_franchise_id_season_week_idx" ON hob_private."context_notes" ("franchise_id","season","week");

ALTER TABLE hob_private."draft_grades" ADD FOREIGN KEY ("build_id") REFERENCES hob_private."stat_builds" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE hob_private."draft_pick_values" ADD FOREIGN KEY ("build_id") REFERENCES hob_private."stat_builds" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE hob_private."draft_pick_values" ADD FOREIGN KEY ("player_id") REFERENCES hob_private."players" ("espn_player_id") DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "draft_pick_values_season_idx" ON hob_private."draft_pick_values" ("season");

CREATE INDEX "draft_pick_values_franchise_id_season_idx" ON hob_private."draft_pick_values" ("franchise_id","season");

ALTER TABLE hob_private."draft_picks" ADD FOREIGN KEY ("team_season_id") REFERENCES hob_private."team_seasons" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE hob_private."draft_picks" ADD FOREIGN KEY ("player_id") REFERENCES hob_private."players" ("espn_player_id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE hob_private."elo_history" ADD FOREIGN KEY ("build_id") REFERENCES hob_private."stat_builds" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "events_event_type_idx" ON hob_private."events" ("event_type");

CREATE INDEX "events_season_week_idx" ON hob_private."events" ("season","week");

ALTER TABLE hob_private."franchise_elo" ADD FOREIGN KEY ("build_id") REFERENCES hob_private."stat_builds" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE hob_private."franchise_managers" ADD FOREIGN KEY ("franchise_id") REFERENCES hob_private."franchises" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE hob_private."h2h_pairs" ADD FOREIGN KEY ("build_id") REFERENCES hob_private."stat_builds" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE hob_private."managers" ADD FOREIGN KEY ("franchise_id") REFERENCES hob_private."franchises" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE hob_private."matchups" ADD FOREIGN KEY ("home_team_season_id") REFERENCES hob_private."team_seasons" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE hob_private."matchups" ADD FOREIGN KEY ("away_team_season_id") REFERENCES hob_private."team_seasons" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE hob_private."notification_prefs" ADD FOREIGN KEY ("manager_id") REFERENCES hob_private."managers" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE hob_private."pickem_picks" ADD FOREIGN KEY ("manager_id") REFERENCES hob_private."managers" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "pickem_picks_season_week_idx" ON hob_private."pickem_picks" ("season","week");

ALTER TABLE hob_private."playoff_odds" ADD FOREIGN KEY ("build_id") REFERENCES hob_private."stat_builds" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "podcast_episodes_season_week_idx" ON hob_private."podcast_episodes" ("season","week");

ALTER TABLE hob_private."poll_options" ADD FOREIGN KEY ("poll_id") REFERENCES hob_private."polls" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "poll_options_poll_id_idx" ON hob_private."poll_options" ("poll_id");

ALTER TABLE hob_private."poll_votes" ADD FOREIGN KEY ("poll_id") REFERENCES hob_private."polls" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE hob_private."poll_votes" ADD FOREIGN KEY ("option_id") REFERENCES hob_private."poll_options" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE hob_private."poll_votes" ADD FOREIGN KEY ("manager_id") REFERENCES hob_private."managers" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "poll_votes_poll_id_manager_id_idx" ON hob_private."poll_votes" ("poll_id","manager_id");

ALTER TABLE hob_private."polls" ADD FOREIGN KEY ("created_by") REFERENCES hob_private."managers" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE hob_private."predictions" ADD FOREIGN KEY ("manager_id") REFERENCES hob_private."managers" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "predictions_season_idx" ON hob_private."predictions" ("season");

CREATE INDEX "preview_episodes_season_week_idx" ON hob_private."preview_episodes" ("season","week");

ALTER TABLE hob_private."push_subscriptions" ADD FOREIGN KEY ("manager_id") REFERENCES hob_private."managers" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "push_subscriptions_manager_id_idx" ON hob_private."push_subscriptions" ("manager_id");

ALTER TABLE hob_private."recap_exemplars" ADD FOREIGN KEY ("recap_id") REFERENCES hob_private."recaps" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "recap_exemplars_captured_at_idx" ON hob_private."recap_exemplars" ("captured_at");

CREATE INDEX "recap_style_guides_is_active_idx" ON hob_private."recap_style_guides" ("is_active");

CREATE INDEX "recaps_season_week_idx" ON hob_private."recaps" ("season","week");

ALTER TABLE hob_private."record_entries" ADD FOREIGN KEY ("build_id") REFERENCES hob_private."stat_builds" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE hob_private."revenge_events" ADD FOREIGN KEY ("build_id") REFERENCES hob_private."stat_builds" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE hob_private."revenge_events" ADD FOREIGN KEY ("player_id") REFERENCES hob_private."players" ("espn_player_id") DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "revenge_events_franchise_id_idx" ON hob_private."revenge_events" ("franchise_id");

CREATE INDEX "revenge_events_franchise_id_player_id_idx" ON hob_private."revenge_events" ("franchise_id","player_id");

CREATE INDEX "revenge_events_franchise_id_against_idx" ON hob_private."revenge_events" ("franchise_id","is_against_former_franchise");

ALTER TABLE hob_private."roster_slots" ADD FOREIGN KEY ("team_season_id") REFERENCES hob_private."team_seasons" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE hob_private."roster_slots" ADD FOREIGN KEY ("player_id") REFERENCES hob_private."players" ("espn_player_id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE hob_private."season_stats" ADD FOREIGN KEY ("build_id") REFERENCES hob_private."stat_builds" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE hob_private."seasons" ADD FOREIGN KEY ("league_id") REFERENCES hob_private."leagues" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE hob_private."slot_scoring_stats" ADD FOREIGN KEY ("build_id") REFERENCES hob_private."stat_builds" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "snapshots_season_view_period_fetched_idx" ON hob_private."snapshots" ("season","view","scoring_period","fetched_at" desc);

CREATE INDEX "snapshots_payload_hash_idx" ON hob_private."snapshots" ("payload_hash");

ALTER TABLE hob_private."team_seasons" ADD FOREIGN KEY ("season") REFERENCES hob_private."seasons" ("season") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE hob_private."team_seasons" ADD FOREIGN KEY ("franchise_id") REFERENCES hob_private."franchises" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE hob_private."team_week" ADD FOREIGN KEY ("build_id") REFERENCES hob_private."stat_builds" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "team_week_franchise_id_season_idx" ON hob_private."team_week" ("franchise_id","season");

ALTER TABLE hob_private."trade_ledger" ADD FOREIGN KEY ("build_id") REFERENCES hob_private."stat_builds" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE hob_private."trade_ledger" ADD FOREIGN KEY ("player_id") REFERENCES hob_private."players" ("espn_player_id") DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "trade_ledger_season_idx" ON hob_private."trade_ledger" ("season");

CREATE INDEX "trade_ledger_transaction_id_idx" ON hob_private."trade_ledger" ("transaction_id");

CREATE INDEX "trade_ledger_receiving_franchise_id_idx" ON hob_private."trade_ledger" ("receiving_franchise_id");

ALTER TABLE hob_private."transaction_items" ADD FOREIGN KEY ("transaction_id") REFERENCES hob_private."transactions" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE hob_private."transaction_items" ADD FOREIGN KEY ("team_season_id") REFERENCES hob_private."team_seasons" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE hob_private."transaction_items" ADD FOREIGN KEY ("player_id") REFERENCES hob_private."players" ("espn_player_id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE hob_private."waiver_acquisitions" ADD FOREIGN KEY ("build_id") REFERENCES hob_private."stat_builds" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE hob_private."waiver_acquisitions" ADD FOREIGN KEY ("player_id") REFERENCES hob_private."players" ("espn_player_id") DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "waiver_acquisitions_season_franchise_id_idx" ON hob_private."waiver_acquisitions" ("season","franchise_id");

CREATE INDEX "waiver_acquisitions_franchise_id_idx" ON hob_private."waiver_acquisitions" ("franchise_id");

REVOKE ALL ON ALL TABLES IN SCHEMA hob_private FROM PUBLIC;

REVOKE ALL ON ALL SEQUENCES IN SCHEMA hob_private FROM PUBLIC;
